---
openapi: 3.0.1
info:
  title: QROPS Transfer
  description: "This API specification describes the data structures and operations\
    \ to compile, submit and retrieve the Qualifying Recognised Overseas Pension Scheme(QROPS)\
    \ Transfer. QROPS Transfers(QT's) will be filed by a Pension Scheme Administrator\
    \ (PSA) or authorised Pension Scheme Practitioner (PSP). \n\nThis API will allow\
    \ synchronous request to ETMP from MDTP (via HIP) to File or Retrieve QROPS Transfer\
    \ for a given Pension Scheme Tax Reference (PSTR).\n\nThere are at present the\
    \ following operations:\n1)\tSubmit or compile one or more QROPS Transfer.\n2)\t\
    Retrieve one or more QROPS Transfer.\n\n**EPID references:** \n \n -HIP OAS EPID1585\
    \ \n\n-EPID1561 \n\n-EPID1562\n\n```\n```\n**Change Log**\n| Version | Date |\
    \ Author | Description |\n|---|-----|------|-----|\n|0.1.0 | 2025-03-28 | Shubham\
    \ Patel | Initial draft (EPID1561 version 0.1 & EPID1562 version 0.1)  |\n |0.1.1\
    \ | 2025-04-16 | Shubham Patel |Updated the API Name\n ||||Updated the enum of\
    \ 'X-Message-Type' in GET Operation\n |0.1.2 | 2025-04-30 | Shubham Patel |Removed\
    \ the Contact section\n |0.2.0 | 2025-05-12 | Shubham Patel |Approved by HIP and\
    \ Digital Team \n |0.2.1 | 2025-06-18 | Shubham Patel |Changes in GET and POST\
    \ operation:Updated the \"correlationid\" Regex, \n ||||Updated the length of\
    \ \"qropsRef\" to '11' and added pattern, Updated the max length of \"title\"\
    \ to '4' \n |0.3.0 | 2025-07-08 | Shubham Patel |Approved by HIP and Digital Team\n\
    |0.3.1 | 2025-10-03 | Manasi Kesarkar |Updated for PODS QT Dec 2025\n||||1. Changes\
    \ for POST Operation: Updated datatype of fields \"reasonNoOverseasTransfer\"\
    \ and \"applicableExclusion\" from string to array for Request structure and updated\
    \ Request example to reflect same. Updated Error Response Schema\n||||2. Changes\
    \ for GET Operation: Updated datatype of fields \"reasonNoOverseasTransfer\" and\
    \ \"applicableExclusion\" from string to array for Response structure and updated\
    \ Response example to reflect same. |1.0.0 | 2025-10-22 | Manasi Kesarkar |Updated\
    \ for PODS QT Dec 2025\n|||| Changes in GET and POST operation:Updated the  correlationidResponseType\"\
    \ Regex"
  termsOfService: http://INSERT_LINK_TO_SLA_HERE
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
  x-integration-catalogue:
    api-type: SIMPLE
    reviewed-date: 2025-10-13T13:13:10.175506913Z
    short-description: Qualifying Recognised Overseas Pension Scheme Transfer
    status: BETA
    platform: HIP
    backends:
    - etmp
    domain: "1"
    sub-domain: "1.11"
servers:
- url: https://api.ipaas.prod.eis.ns2p.corp.hmrc.gov.uk/etmp
  description: Corporate - Production
- url: https://api.ipaas.preprod.eis.ns2p.corp.hmrc.gov.uk/etmp
  description: Corporate – Pre-Production
- url: https://api.ipaas.test.eis.ns2n.corp.hmrc.gov.uk/etmp
  description: Corporate - Test
- url: https://hip.ws.hmrc.gov.uk/etmp
  description: MDTP - Production
- url: https://hip.ws.ibt.hmrc.gov.uk/etmp
  description: MDTP - QA
security:
- oAuth2:
  - write:qrops-transfer
  - read:qrops-transfer
tags:
- name: pods-qrops-transfer
  description: Pensions Online Digital Service - Qualifying Recognised Overseas Pension
    Scheme Transfer
paths:
  /RESTAdapter/pods/reports/qrops-transfer:
    get:
      tags:
      - pods-qrops-transfer
      summary: Consumer to ETMP QROPS Transfer GET Operation
      description: "This operation covers actions to Get QROPS Transfer. QTs will\
        \ be displayed by a Pension Scheme Administrator (PSA) or authorised Pension\
        \ Scheme Practitioner (PSP).\n \nThe call is synchronous.\n \nFor the successful\
        \ scenario the API will return successful response. \nFor the unsuccessful\
        \ scenario, the API will return error messages from ETMP or ETMP's middleware.\n\
        \n**EPID reference:** \n- EPID1562\n- HIP OAS EPID1585"
      parameters:
      - name: correlationid
        in: header
        description: |
          Unique alphanumeric number used for correlation purposes, generated by the originating system and conforming to 36-character UUID (formatted).
        required: true
        schema:
          pattern: "^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$"
          type: string
        deprecated: false
        style: simple
        explode: false
        example: f0bd1f32-de51-45cc-9b18-0520d6e3ab1a
      - name: fbNumber
        in: query
        description: Form Bundle Number (cannot be used with QTNumber and VersionNumber)
        required: false
        schema:
          pattern: "^[0-9]{12}$"
          type: string
        allowEmptyValue: false
        deprecated: false
        style: form
        explode: true
        example: "123456789012"
      - name: pstr
        in: query
        description: Scheme Identifier (must be combined with FBNumber OR (QTNumber
          AND VersionNumber))
        required: true
        schema:
          pattern: "^[0-9]{8}[A-Z]{2}$"
          type: string
        allowEmptyValue: false
        deprecated: false
        style: form
        explode: true
        example: 12345678AB
      - name: qtNumber
        in: query
        description: QT Reference Number (must be used with VersionNumber)
        required: false
        schema:
          format: "QT[0-9]{6}"
          type: string
        allowEmptyValue: false
        deprecated: false
        style: form
        explode: true
        example: QT123456
      - name: versionNumber
        in: query
        description: Version Number (must be used with QTNumber)
        required: false
        schema:
          pattern: "^[0-9]{3}$"
          type: string
        allowEmptyValue: false
        deprecated: false
        style: form
        explode: true
        example: "001"
      - name: X-Message-Type
        in: header
        required: true
        schema:
          enum:
          - GetQROPSTransfer
          type: string
        deprecated: false
        style: simple
        explode: false
      - name: X-Originating-System
        in: header
        description: "System that is the originator of the message. \n"
        required: true
        schema:
          maxLength: 30
          minLength: 1
          type: string
        deprecated: false
        style: simple
        explode: false
        example: MDTP
      - name: X-Receipt-Date
        in: header
        description: "The time the message was created by the system sending the message.\
          \ The value should follow this date-time pattern, and be represented in\
          \ the UTC time zone: yyyy-MM-ddTHH:mm:ssZ"
        required: true
        schema:
          format: date-time
          type: string
        deprecated: false
        style: simple
        explode: false
        example: 2025-01-30T23:59:59Z
      - name: X-Regime-Type
        in: header
        required: true
        schema:
          enum:
          - PODS
          type: string
        deprecated: false
        style: simple
        explode: false
      - name: X-Transmitting-System
        in: header
        description: "Intermediary system that performs the transmission of the message.\
          \ \n-\tFixed value of 'HIP' required.\n"
        required: true
        schema:
          enum:
          - HIP
          type: string
        deprecated: false
        style: simple
        explode: false
      responses:
        "200":
          description: ETMP has successfully accepted the request and will display
            QROPS Transfer.
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/podsQROPSGetResponseSchemaSuccess'
              examples:
                Sample Response Success:
                  $ref: '#/components/examples/podsQROPSGetSampleResponseSuccess'
        "400":
          description: Bad Request
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                required:
                - origin
                - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                    - $ref: '#/components/schemas/HIP-failureResponse'
                    - $ref: '#/components/schemas/responseSystemErrorType'
                additionalProperties: false
              examples:
                Bad Request:
                  value:
                    origin: HoD
                    response:
                      error:
                        code: "400"
                        logID: C0000AB8190C86300000000200006836
                        message: "Invalid&#x20;JSON&#x20;message&#x20;content&#x20;used&#x3b;&#x20;Message&#x3a;&#x20;&quot;Expected&#x20;a&#x20;&#x27;,&#x27;&#x20;or&#x20;&#x27;&#x7d;&#x27;&#x20;at&#x20;character&#x20;93&#x20;of&#x20;&#x7b;&#xa;&#x9;&quot;idType&quot;&#x3a;&#x20;&quot;EMPREF&quot;,&#xa;&#x9;&quot;idValue&quot;&#x3a;&#x20;&quot;864FZ00049&quot;,&#xa;&#x9;&quot;regimeType&quot;&#x3a;&#x20;&quot;PAYE&quot;,&#xa;&#x9;&quot;lockReason&quot;&#x3a;&#x20;&quot;8&quot;&#xa;&#x9;&quot;chargeReferences&quot;&#x3a;&#x20;&#x5b;&#xa;&#x9;&#x9;&quot;XM123456789812&quot;,&#xa;&#x9;&#x9;&quot;XM123456781234&quot;,&#xa;&#x9;&#x9;&quot;XC123111781234&quot;&#xa;&#x9;&#x5d;,&#x9;&#xa;&#x9;&quot;createNote&quot;&#x3a;&#x20;true,&#xa;&#x9;&quot;noteType&quot;&#x3a;&#x20;&quot;TTP&quot;,&#xa;&#x9;&quot;noteLines&quot;&#x3a;&#x20;&#x5b;&#xa;&#x9;&#x9;&quot;paymentPlanType&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;TTP&quot;,&#xa;&#x9;&#x9;&quot;arrangementAgreedDate&#x3a;&#x20;2022-02-01&quot;,&#xa;&#x9;&#x9;&quot;arrangementChannel&#x3a;&#x20;&#x20;&#x20;&#x20;ePAYE&quot;,&#xa;&#x9;&#x9;&quot;firstPaymentAmount&#x3a;&#x20;&#x20;&#x20;&#x20;1234.56&quot;,&#xa;&#x9;&#x9;&quot;firstPaymentDate&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;2022-03-01&quot;,&#xa;&#x9;&#x9;&quot;regularPaymentAmount&#x3a;&#x20;&#x20;1000&quot;,&#xa;&#x9;&#x9;&quot;paymentFrequency&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;Monthly&quot;,&#xa;&#x9;&#x9;&quot;arrangementReviewDate&#x3a;&#x20;2022-11-02&quot;,&#xa;&#x9;&#x9;&quot;ddiReference&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;123456789012&quot;&#xa;&#x9;&#x5d;&#xa;&#x7d;&quot;"
                HIP-originResponse:
                  description: HIP-originResponse
                  value:
                    origin: HIP
                    response:
                    - type: Type of Failure
                      reason: Reason for Failure
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "415":
          description: Unsupported media-type
        "422":
          description: "ETMP validation errors. \nErrors of this kind indicate that\
            \ ETMP successfully received the data without any technical issues, however\
            \ it is unable to process the data further for the reason given by the\
            \ code and text.\n\n```\n[ code | text]\n001 | REGIME missing or invalid\n\
            003 | Request could not be processed\n049 | Invalid PSTR\n055 | Form Bundle\
            \ not found for the given PSTR <PSTR>\n182 | Invalid QT Reference Provided\n\
            183 | No QT found in ETMP for the requested details\n999 | Technical Error\n\
            \n"
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/podsQROPSGetEtmpErrorsType'
              examples:
                Business Validation Error:
                  $ref: '#/components/examples/podsQROPSGetSample422ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                required:
                - origin
                - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                    - $ref: '#/components/schemas/HIP-failureResponse'
                    - $ref: '#/components/schemas/responseSystemErrorType'
                additionalProperties: false
              examples:
                Internal Server Error:
                  value:
                    origin: HoD
                    response:
                      error:
                        code: "500"
                        logID: C0000AB8190C8E1F000000C700006836
                        message: Error&#x20;while&#x20;sending&#x20;message&#x20;to&#x20;module&#x20;processor&#x3a;&#x20;Sender&#x20;Channel&#x20;&#x27;CCOS_01_REST_Out_eSSTTP_PaymentLock_Set&#x27;&#x20;&#x28;ID&#x3a;&#x20;624ce8b4f8773eb0b227f1a90b6f40a5&#x29;&#x3a;&#x20;Catching&#x20;exception&#x20;calling&#x20;messaging&#x20;system&#x3a;&#x20;com.sap.aii.af.sdk.xi.srt.BubbleException&#x3a;&#x20;System&#x20;Error&#x20;Received.&#x20;HTTP&#x20;Status&#x20;Code&#x20;&#x3d;&#x20;200&#x3a;&#x20;However&#x20;System&#x20;Error&#x20;received&#x20;in&#x20;payload&#x20;ErrorCode&#x20;&#x3d;&#x20;INCORRECT_PAYLOAD_DATA&#x20;ErrorCategory&#x20;&#x3d;&#x20;XIServer&#x20;Parameter1&#x20;&#x3d;&#x20;&#x20;Parameter2&#x20;&#x3d;&#x20;&#x20;Parameter3&#x20;&#x3d;&#x20;&#x20;Parameter4&#x20;&#x3d;&#x20;&#x20;Additional&#x20;text&#x20;&#x3d;&#x20;&#x20;ErrorStack&#x20;&#x3d;&#x20;Error&#x20;while&#x20;processing&#x20;message&#x20;payload&#xa;&#xa;An&#x20;error&#x20;occurred&#x20;when&#x20;deserializing&#x20;in&#x20;the&#x20;simple&#x20;transformation&#x20;program&#x20;&#x2f;1SAI&#x2f;SAS476436EAEE64FB2B9096&#xa;Value&#x20;is&#x20;longer&#x20;than&#x20;the&#x20;maximum&#x20;permitted&#x20;length&#x20;15&#x3a;&#x20;&quot;864FZ077777770049&quot;&#xa;&#x20;&#x5b;http&#x3a;&#x2f;&#x2f;sap.com&#x2f;xi&#x2f;XI&#x2f;Message&#x2f;30&#x5e;Error&#x20;&quot;INCORRECT_PAYLOAD_DATA&quot;&#x5d;
                HIP-originResponse:
                  description: HIP-originResponse
                  value:
                    origin: HIP
                    response:
                    - type: Type of Failure
                      reason: Reason for Failure
        "503":
          description: Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
      deprecated: false
    post:
      tags:
      - pods-qrops-transfer
      summary: Consumer to ETMP QROPS Transfer Submit and Compile Operation
      description: "This operation covers actions to compile and submit the QROPS\
        \ Transfer. QT's will be filed by a Pension Scheme Administrator (PSA) or\
        \ authorised Pension Scheme Practitioner (PSP).\n \nThe call is synchronous.\n\
        \ \nFor the successful scenario the API will return Processing date and Form\
        \ bundle number. \nFor the unsuccessful scenario, the API will return error\
        \ messages from ETMP or ETMP's middleware.\n\n**EPID reference:** \n- EPID1561\n\
        - HIP OAS EPID1585"
      operationId: submitOrCompileQROPSTransfer
      parameters:
      - name: correlationid
        in: header
        description: |
          Unique alphanumeric number used for correlation purposes, generated by the originating system and conforming to 36-character UUID (formatted).
        required: true
        schema:
          pattern: "^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$"
          type: string
        deprecated: false
        style: simple
        explode: false
        example: f0bd1f32-de51-45cc-9b18-0520d6e3ab1a
      - name: X-Message-Type
        in: header
        required: true
        schema:
          enum:
          - FileQROPSTransfer
          type: string
        deprecated: false
        style: simple
        explode: false
      - name: X-Originating-System
        in: header
        description: "System that is the originator of the message. \n"
        required: true
        schema:
          maxLength: 30
          minLength: 1
          type: string
        deprecated: false
        style: simple
        explode: false
        example: MDTP
      - name: X-Receipt-Date
        in: header
        description: "The time the message was created by the system sending the message.\
          \ The value should follow this date-time pattern, and be represented in\
          \ the UTC time zone: yyyy-MM-ddTHH:mm:ssZ"
        required: true
        schema:
          format: date-time
          type: string
        deprecated: false
        style: simple
        explode: false
        example: 2025-01-30T23:59:59Z
      - name: X-Regime-Type
        in: header
        required: true
        schema:
          enum:
          - PODS
          type: string
        deprecated: false
        style: simple
        explode: false
      - name: X-Transmitting-System
        in: header
        description: "Intermediary system that performs the transmission of the message.\
          \ \n-\tFixed value of 'HIP' required.\n"
        required: true
        schema:
          enum:
          - HIP
          type: string
        deprecated: false
        style: simple
        explode: false
      requestBody:
        description: Request structure
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/podsQROPSCreateRequestSchema'
            examples:
              Sample Request Data:
                $ref: '#/components/examples/podsQROPSCreateSampleRequestData'
        required: false
      responses:
        "201":
          description: ETMP has successfully accepted the request and will process
            to file QROPS Transfer.
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/podsQROPSCreateResponseSchemaSuccess'
              examples:
                Sample Response Success:
                  $ref: '#/components/examples/podsQROPSCreateSampleResponseSuccess'
        "400":
          description: Bad Request
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                required:
                - origin
                - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                    - $ref: '#/components/schemas/HIP-failureResponse'
                    - $ref: '#/components/schemas/responseSystemErrorType'
                additionalProperties: false
              examples:
                Bad Request:
                  value:
                    origin: HoD
                    response:
                      error:
                        code: "400"
                        logID: C0000AB8190C86300000000200006836
                        message: "Invalid&#x20;JSON&#x20;message&#x20;content&#x20;used&#x3b;&#x20;Message&#x3a;&#x20;&quot;Expected&#x20;a&#x20;&#x27;,&#x27;&#x20;or&#x20;&#x27;&#x7d;&#x27;&#x20;at&#x20;character&#x20;93&#x20;of&#x20;&#x7b;&#xa;&#x9;&quot;idType&quot;&#x3a;&#x20;&quot;EMPREF&quot;,&#xa;&#x9;&quot;idValue&quot;&#x3a;&#x20;&quot;864FZ00049&quot;,&#xa;&#x9;&quot;regimeType&quot;&#x3a;&#x20;&quot;PAYE&quot;,&#xa;&#x9;&quot;lockReason&quot;&#x3a;&#x20;&quot;8&quot;&#xa;&#x9;&quot;chargeReferences&quot;&#x3a;&#x20;&#x5b;&#xa;&#x9;&#x9;&quot;XM123456789812&quot;,&#xa;&#x9;&#x9;&quot;XM123456781234&quot;,&#xa;&#x9;&#x9;&quot;XC123111781234&quot;&#xa;&#x9;&#x5d;,&#x9;&#xa;&#x9;&quot;createNote&quot;&#x3a;&#x20;true,&#xa;&#x9;&quot;noteType&quot;&#x3a;&#x20;&quot;TTP&quot;,&#xa;&#x9;&quot;noteLines&quot;&#x3a;&#x20;&#x5b;&#xa;&#x9;&#x9;&quot;paymentPlanType&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;TTP&quot;,&#xa;&#x9;&#x9;&quot;arrangementAgreedDate&#x3a;&#x20;2022-02-01&quot;,&#xa;&#x9;&#x9;&quot;arrangementChannel&#x3a;&#x20;&#x20;&#x20;&#x20;ePAYE&quot;,&#xa;&#x9;&#x9;&quot;firstPaymentAmount&#x3a;&#x20;&#x20;&#x20;&#x20;1234.56&quot;,&#xa;&#x9;&#x9;&quot;firstPaymentDate&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;2022-03-01&quot;,&#xa;&#x9;&#x9;&quot;regularPaymentAmount&#x3a;&#x20;&#x20;1000&quot;,&#xa;&#x9;&#x9;&quot;paymentFrequency&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;Monthly&quot;,&#xa;&#x9;&#x9;&quot;arrangementReviewDate&#x3a;&#x20;2022-11-02&quot;,&#xa;&#x9;&#x9;&quot;ddiReference&#x3a;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;&#x20;123456789012&quot;&#xa;&#x9;&#x5d;&#xa;&#x7d;&quot;"
                HIP-originResponse:
                  description: HIP-originResponse
                  value:
                    origin: HIP
                    response:
                    - type: Type of Failure
                      reason: Reason for Failure
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "415":
          description: Unsupported media-type
        "422":
          description: "ETMP validation errors. \nErrors of this kind indicate that\
            \ ETMP successfully received the data without any technical issues, however\
            \ it is unable to process the data further for the reason given by the\
            \ code and text.\n\n```\n[ code | text]\n001 | REGIME missing or invalid\n\
            003 | Request could not be processed\n004 | Duplicate submission acknowledgment\
            \ reference\n046 | Invalid PSAID\n058 | No relationship exists between\
            \ the PSAID and the scheme\n090 | Invalid PSPID <PSPID>\n091 | No relationship\
            \ exists between the PSPID <PSPID> and the scheme <PSTR>\n092 | PSAID\
            \ is mandatory if the declaration is provided by PSP\n093 | PSP <PSPID>\
            \ is not authorized by PSA <PSAID>\n171 | Declaration is missing\n182\
            \ | Invalid QT Reference Provided\n999 | Technical Error\n\n"
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/podsQROPSCreateEtmpErrorsType'
              examples:
                Business Validation Error:
                  $ref: '#/components/examples/podsQROPSCreateSample422ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            correlationid:
              $ref: '#/components/headers/correlationidResponseType'
          content:
            application/json:
              schema:
                required:
                - origin
                - response
                type: object
                properties:
                  origin:
                    $ref: '#/components/schemas/HIP-originEnum'
                  response:
                    oneOf:
                    - $ref: '#/components/schemas/HIP-failureResponse'
                    - $ref: '#/components/schemas/responseSystemErrorType'
                additionalProperties: false
              examples:
                Internal Server Error:
                  value:
                    origin: HoD
                    response:
                      error:
                        code: "500"
                        logID: C0000AB8190C8E1F000000C700006836
                        message: Error&#x20;while&#x20;sending&#x20;message&#x20;to&#x20;module&#x20;processor&#x3a;&#x20;Sender&#x20;Channel&#x20;&#x27;CCOS_01_REST_Out_eSSTTP_PaymentLock_Set&#x27;&#x20;&#x28;ID&#x3a;&#x20;624ce8b4f8773eb0b227f1a90b6f40a5&#x29;&#x3a;&#x20;Catching&#x20;exception&#x20;calling&#x20;messaging&#x20;system&#x3a;&#x20;com.sap.aii.af.sdk.xi.srt.BubbleException&#x3a;&#x20;System&#x20;Error&#x20;Received.&#x20;HTTP&#x20;Status&#x20;Code&#x20;&#x3d;&#x20;200&#x3a;&#x20;However&#x20;System&#x20;Error&#x20;received&#x20;in&#x20;payload&#x20;ErrorCode&#x20;&#x3d;&#x20;INCORRECT_PAYLOAD_DATA&#x20;ErrorCategory&#x20;&#x3d;&#x20;XIServer&#x20;Parameter1&#x20;&#x3d;&#x20;&#x20;Parameter2&#x20;&#x3d;&#x20;&#x20;Parameter3&#x20;&#x3d;&#x20;&#x20;Parameter4&#x20;&#x3d;&#x20;&#x20;Additional&#x20;text&#x20;&#x3d;&#x20;&#x20;ErrorStack&#x20;&#x3d;&#x20;Error&#x20;while&#x20;processing&#x20;message&#x20;payload&#xa;&#xa;An&#x20;error&#x20;occurred&#x20;when&#x20;deserializing&#x20;in&#x20;the&#x20;simple&#x20;transformation&#x20;program&#x20;&#x2f;1SAI&#x2f;SAS476436EAEE64FB2B9096&#xa;Value&#x20;is&#x20;longer&#x20;than&#x20;the&#x20;maximum&#x20;permitted&#x20;length&#x20;15&#x3a;&#x20;&quot;864FZ077777770049&quot;&#xa;&#x20;&#x5b;http&#x3a;&#x2f;&#x2f;sap.com&#x2f;xi&#x2f;XI&#x2f;Message&#x2f;30&#x5e;Error&#x20;&quot;INCORRECT_PAYLOAD_DATA&quot;&#x5d;
                HIP-originResponse:
                  description: HIP-originResponse
                  value:
                    origin: HIP
                    response:
                    - type: Type of Failure
                      reason: Reason for Failure
        "503":
          description: Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/HIP-originResponse'
      deprecated: false
components:
  schemas:
    aboutReceivingQROPSType:
      type: object
      properties:
        qropsFullName:
          $ref: '#/components/schemas/string160Type'
        qropsRef:
          description: QROPS Reference
          pattern: "^QROPS[0-9]{6}$"
          type: string
        receivingQropsAddress:
          $ref: '#/components/schemas/addressType'
        receivingQropsEstablishedDetails:
          $ref: '#/components/schemas/receivingQropsEstablishedDetailsType'
        qropsSchemeManagerType:
          $ref: '#/components/schemas/qropsSchemeManagerType'
      additionalProperties: false
    addressType:
      type: object
      properties:
        addressLine1:
          $ref: '#/components/schemas/string35Type'
        addressLine2:
          $ref: '#/components/schemas/string35Type'
        addressLine3:
          $ref: '#/components/schemas/string35Type'
        addressLine4:
          $ref: '#/components/schemas/string35Type'
        addressLine5:
          $ref: '#/components/schemas/string35Type'
        ukPostCode:
          $ref: '#/components/schemas/ukPostCodeType'
        country:
          $ref: '#/components/schemas/countryCodeType'
      additionalProperties: false
    booleanType:
      enum:
      - "No"
      - "Yes"
      type: string
    countryCodeType:
      maxLength: 2
      minLength: 2
      enum:
      - AD
      - AE
      - AF
      - AG
      - AI
      - AL
      - AM
      - AN
      - AO
      - AQ
      - AR
      - AS
      - AT
      - AU
      - AW
      - AX
      - AZ
      - BA
      - BB
      - BD
      - BE
      - BF
      - BG
      - BH
      - BI
      - BJ
      - BL
      - BM
      - BN
      - BO
      - BQ
      - BR
      - BS
      - BT
      - BV
      - BW
      - BY
      - BZ
      - CA
      - CC
      - CD
      - CF
      - CG
      - CH
      - CI
      - CK
      - CL
      - CM
      - CN
      - CO
      - CR
      - CS
      - CU
      - CV
      - CW
      - CX
      - CY
      - CZ
      - DE
      - DJ
      - DK
      - DM
      - DO
      - DZ
      - EC
      - EE
      - EG
      - EH
      - ER
      - ES
      - ET
      - EU
      - FC
      - FI
      - FJ
      - FK
      - FM
      - FO
      - FR
      - GA
      - GB
      - GD
      - GE
      - GF
      - GG
      - GH
      - GI
      - GL
      - GM
      - GN
      - GP
      - GQ
      - GR
      - GS
      - GT
      - GU
      - GW
      - GY
      - HK
      - HM
      - HN
      - HR
      - HT
      - HU
      - ID
      - IE
      - IL
      - IM
      - IN
      - IO
      - IQ
      - IR
      - IS
      - IT
      - JE
      - JM
      - JO
      - JP
      - KE
      - KG
      - KH
      - KI
      - KM
      - KN
      - KP
      - KR
      - KW
      - KY
      - KZ
      - LA
      - LB
      - LC
      - LI
      - LK
      - LR
      - LS
      - LT
      - LU
      - LV
      - LY
      - MA
      - MC
      - MD
      - ME
      - MF
      - MG
      - MH
      - MK
      - ML
      - MM
      - MN
      - MO
      - MP
      - MQ
      - MR
      - MS
      - MT
      - MU
      - MV
      - MW
      - MX
      - MY
      - MZ
      - NA
      - NC
      - NE
      - NF
      - NG
      - NI
      - NL
      - "NO"
      - NP
      - NR
      - NT
      - NU
      - NZ
      - OM
      - OR
      - PA
      - PE
      - PF
      - PG
      - PH
      - PK
      - PL
      - PM
      - PN
      - PR
      - PS
      - PT
      - PW
      - PY
      - QA
      - RE
      - RO
      - RS
      - RU
      - RW
      - SA
      - SB
      - SC
      - SD
      - SE
      - SG
      - SH
      - SI
      - SJ
      - SK
      - SL
      - SM
      - SN
      - SO
      - SR
      - SS
      - ST
      - SV
      - SX
      - SY
      - SZ
      - TC
      - TD
      - TF
      - TG
      - TH
      - TJ
      - TK
      - TL
      - TM
      - TN
      - TO
      - TP
      - TR
      - TT
      - TV
      - TW
      - TZ
      - UA
      - UG
      - UM
      - UN
      - US
      - UY
      - UZ
      - VA
      - VC
      - VE
      - VG
      - VI
      - VN
      - VU
      - WF
      - WS
      - YE
      - YT
      - ZA
      - ZM
      - ZW
      - ZZ
      type: string
    currencyType:
      description: "decimal between 0.00 and 999,999,999.99"
      multipleOf: 0.01
      maximum: 999999999.99
      minimum: -99999999.99
      type: number
    declarationType:
      description: Declaration is Mandatory if the QT form is Submitted
      type: object
      properties:
        declaration1:
          description: Possible values;- true=  Selected-false=  Not Selected
          type: boolean
        declaration2:
          description: Possible values;- true=  Selected-false=  Not Selected
          type: boolean
      additionalProperties: false
    integer7DigitsMinimum0Type:
      description: Integer with minimum 0 and maximum 9999999
      maximum: 9999999
      minimum: 0
      type: integer
    memberDetailsType:
      required:
      - foreName
      - lastName
      type: object
      properties:
        title:
          maxLength: 4
          minLength: 1
          type: string
        foreName:
          $ref: '#/components/schemas/string35Type'
        lastName:
          $ref: '#/components/schemas/string35Type'
        dateOfBirth:
          format: date
          type: string
        nino:
          $ref: '#/components/schemas/ninoType'
        reasonNoNINO:
          $ref: '#/components/schemas/string160Type'
        principalResAddDetails:
          type: object
          properties:
            addressDetails:
              $ref: '#/components/schemas/addressType'
            poBoxNumber:
              $ref: '#/components/schemas/string35Type'
          additionalProperties: false
        memberResidencyDetails:
          $ref: '#/components/schemas/memberResidencyDetailsType'
      additionalProperties: false
    memberResidencyDetailsType:
      type: object
      properties:
        memUkResident:
          $ref: '#/components/schemas/booleanType'
        memEverUkResident:
          $ref: '#/components/schemas/booleanType'
        lastPrincipalAddDetails:
          type: object
          properties:
            addressDetails:
              $ref: '#/components/schemas/addressType'
            dateMemberLeftUk:
              format: date
              type: string
          additionalProperties: false
      additionalProperties: false
    ninoType:
      pattern: "^([A-Z]{2}[0-9]{6}[A-Z]{1})$"
      type: string
    otherAssetsType:
      minItems: 0
      type: array
      items:
        type: object
        properties:
          recordVersion:
            $ref: '#/components/schemas/versionType'
          assetValue:
            $ref: '#/components/schemas/currencyType'
          assetDescription:
            $ref: '#/components/schemas/string160Type'
        additionalProperties: false
    podsQROPSCreateEtmpErrorsType:
      type: object
      properties:
        errors:
          description: ETMP Business Validation Error Response
          required:
          - code
          - processingDate
          - text
          type: object
          properties:
            processingDate:
              format: date-time
              type: string
            code:
              enum:
              - "001"
              - "003"
              - "004"
              - "046"
              - "058"
              - "090"
              - "091"
              - "092"
              - "093"
              - "171"
              - "182"
              - "999"
              type: string
            text:
              maxLength: 100
              minLength: 1
              type: string
          additionalProperties: false
      additionalProperties: false
    podsQROPSCreateRequestSchema:
      required:
      - reportDetails
      type: object
      properties:
        reportDetails:
          $ref: '#/components/schemas/reportDetailsType'
        transferringMember:
          required:
          - memberDetails
          type: object
          properties:
            memberDetails:
              $ref: '#/components/schemas/memberDetailsType'
          additionalProperties: false
        transferDetails:
          $ref: '#/components/schemas/transferDetailType'
        aboutReceivingQROPS:
          $ref: '#/components/schemas/aboutReceivingQROPSType'
        qtDeclaration:
          $ref: '#/components/schemas/qtDeclarationType'
        psaDeclaration:
          $ref: '#/components/schemas/declarationType'
        pspDeclaration:
          $ref: '#/components/schemas/declarationType'
      additionalProperties: false
    podsQROPSCreateResponseSchemaSuccess:
      required:
      - success
      type: object
      properties:
        success:
          required:
          - formBundleNumber
          - processingDate
          - qtReference
          type: object
          properties:
            processingDate:
              format: date-time
              type: string
            formBundleNumber:
              maxLength: 15
              minLength: 1
              type: string
            qtReference:
              description: QROPS Transfer Reference
              pattern: "^(QT[0-9]{6})$"
              type: string
          additionalProperties: false
      additionalProperties: false
    podsQROPSGetEtmpErrorsType:
      type: object
      properties:
        errors:
          description: ETMP Business Validation Error Response
          required:
          - code
          - processingDate
          - text
          type: object
          properties:
            processingDate:
              format: date-time
              type: string
            code:
              enum:
              - "001"
              - "003"
              - "049"
              - "055"
              - "182"
              - "183"
              - "999"
              type: string
            text:
              maxLength: 100
              minLength: 1
              type: string
          additionalProperties: false
      additionalProperties: false
    podsQROPSGetResponseSchemaSuccess:
      required:
      - success
      type: object
      properties:
        success:
          required:
          - processingDate
          - pstr
          - qtDetails
          type: object
          properties:
            processingDate:
              format: date-time
              type: string
            pstr:
              $ref: '#/components/schemas/pstrType'
            qtDetails:
              $ref: '#/components/schemas/qtDetailsType'
            transferringMember:
              required:
              - memberDetails
              type: object
              properties:
                memberDetails:
                  $ref: '#/components/schemas/memberDetailsType'
              additionalProperties: false
            transferDetails:
              $ref: '#/components/schemas/transferDetailType'
            aboutReceivingQROPS:
              $ref: '#/components/schemas/aboutReceivingQROPSType'
            qtDeclaration:
              $ref: '#/components/schemas/qtDeclarationType'
            psaDeclaration:
              $ref: '#/components/schemas/declarationType'
            pspDeclaration:
              $ref: '#/components/schemas/declarationType'
          additionalProperties: false
      additionalProperties: false
    propertyAssetsType:
      minItems: 0
      type: array
      items:
        type: object
        properties:
          recordVersion:
            $ref: '#/components/schemas/versionType'
          propertyAddress:
            $ref: '#/components/schemas/addressType'
          propValue:
            $ref: '#/components/schemas/currencyType'
          propDescription:
            $ref: '#/components/schemas/string160Type'
        additionalProperties: false
    pstrType:
      description: Pension Scheme Tax Reference
      pattern: "^([0-9]{8}[A-Z]{2})$"
      type: string
    qropsIndividualType:
      type: object
      properties:
        individualTitle:
          maxLength: 4
          minLength: 1
          type: string
        individualForename:
          $ref: '#/components/schemas/string35Type'
        individualSurname:
          $ref: '#/components/schemas/string35Type'
      additionalProperties: false
    qropsOrganisationType:
      type: object
      properties:
        orgName:
          $ref: '#/components/schemas/string160Type'
        orgTitle:
          maxLength: 4
          minLength: 1
          type: string
        orgForename:
          $ref: '#/components/schemas/string35Type'
        orgSurname:
          $ref: '#/components/schemas/string35Type'
      additionalProperties: false
    qropsSchemeManagerType:
      type: object
      properties:
        schemeManagerType:
          description: Is the scheme manager an individual or organisation ? 01 -
            Individual 02 - Organisation
          enum:
          - "01"
          - "02"
          type: string
        schemeManagerAddress:
          $ref: '#/components/schemas/addressType'
        schemeManagerEmail:
          format: email
          description: Scheme Managers email address
          type: string
        schemeManagerPhone:
          $ref: '#/components/schemas/string160Type'
        qropsIndividual:
          $ref: '#/components/schemas/qropsIndividualType'
        qropsOrganisation:
          $ref: '#/components/schemas/qropsOrganisationType'
      additionalProperties: false
    qtDeclarationType:
      type: object
      properties:
        submittedBy:
          $ref: '#/components/schemas/submittedByType'
        submitterId:
          description: Identifier of the PSA or PSP who submitted the QT.  PSAID or
            PSPID.
          maxLength: 8
          minLength: 8
          pattern: "^([A|0|1|2]{1}[0-9]{7})$"
          type: string
        psaId:
          description: PSAID Reference number is mandatory if the declaration is submitted
            by PSP.
          maxLength: 8
          minLength: 8
          pattern: "^(A[0-9]{7})$"
          type: string
      additionalProperties: false
    qtDetailsType:
      required:
      - qtReference
      - qtStatus
      - qtVersion
      - receiptDate
      type: object
      properties:
        qtVersion:
          $ref: '#/components/schemas/versionType'
        qtStatus:
          description: "Possible values : Compiled, Submitted"
          enum:
          - Compiled
          - Submitted
          type: string
        receiptDate:
          format: date-time
          description: Compilation or Submission Date
          type: string
        qtReference:
          description: QROPS Transfer Reference
          pattern: "^(QT[0-9]{6})$"
          type: string
        qtTransferDate:
          format: date
          description: QT Transfer Date
          type: string
        qtDigitalStatus:
          $ref: '#/components/schemas/string35Type'
      additionalProperties: false
    quotedSharesType:
      minItems: 0
      type: array
      items:
        type: object
        properties:
          recordVersion:
            $ref: '#/components/schemas/versionType'
          quotedValue:
            $ref: '#/components/schemas/currencyType'
          quotedShareTotal:
            $ref: '#/components/schemas/integer7DigitsMinimum0Type'
          quotedCompany:
            $ref: '#/components/schemas/string160Type'
          quotedClass:
            $ref: '#/components/schemas/string160Type'
        additionalProperties: false
    receivingQropsEstablishedDetailsType:
      type: object
      properties:
        qropsEstablished:
          $ref: '#/components/schemas/countryCodeType'
        qropsEstablishedOther:
          $ref: '#/components/schemas/string35Type'
      additionalProperties: false
    reportDetailsType:
      required:
      - pstr
      - qtStatus
      type: object
      properties:
        pstr:
          $ref: '#/components/schemas/pstrType'
        qtStatus:
          description: "Possible values : Compiled, Submitted"
          enum:
          - Compiled
          - Submitted
          type: string
        qtReference:
          description: QROPS Transfer Reference
          pattern: "^(QT[0-9]{6})$"
          type: string
        qtDigitalStatus:
          $ref: '#/components/schemas/string35Type'
      additionalProperties: false
    responseSystemErrorType:
      type: object
      properties:
        error:
          description: SAP PI System Error Response
          required:
          - code
          - logID
          - message
          type: object
          properties:
            code:
              enum:
              - "400"
              - "500"
              type: string
            message:
              maxLength: 5000
              minLength: 1
              type: string
            logID:
              maxLength: 32
              minLength: 32
              pattern: "^[A-F0-9]{32}$"
              type: string
          additionalProperties: false
      additionalProperties: false
    string160Type:
      maxLength: 160
      minLength: 1
      pattern: "^(.{1,160})$"
      type: string
    string35Type:
      maxLength: 35
      minLength: 1
      pattern: "^(.{1,35})$"
      type: string
    submittedByType:
      description: "Possible : Values are PSA or PSP"
      enum:
      - PSA
      - PSP
      type: string
    taxableOverseasTransferDetailsType:
      type: object
      properties:
        whyTaxableOT:
          description: "Possible values;\r\n01 - Transfer exceeds member's overseas\
            \ transfer allowance (S244IA) and there is an applicable exclusion (Sections\
            \ 244B to 244F Finance Act 2004)\r\n02 - There is no applicable exclusion\
            \ (S244AC)"
          enum:
          - "01"
          - "02"
          type: string
        applicableExclusion:
          description: Possible values;\n\n01 - The QROPS is an occupational pension
            scheme and the individual is an employee of the sponsoring employer \n02
            - The QROPS is an overseas public service scheme and the individual is
            employed by that public service\n03 - The QROPS is a pension scheme of
            an international organisation and the individual is employed by that international
            organisation. \n04 - Both the individual and QROPS are resident in the
            same country
          maxItems: 4
          minItems: 0
          uniqueItems: true
          type: array
          items:
            enum:
            - "01"
            - "02"
            - "03"
            - "04"
            type: string
        amountTaxDeducted:
          $ref: '#/components/schemas/currencyType'
        transferMinusTax:
          $ref: '#/components/schemas/currencyType'
      additionalProperties: false
    transferDetailType:
      type: object
      properties:
        recordVersion:
          $ref: '#/components/schemas/versionType'
        transferAmount:
          $ref: '#/components/schemas/currencyType'
        allowanceBeforeTransfer:
          $ref: '#/components/schemas/currencyType'
        dateMemberTransferred:
          format: date
          description: 'Enter the date the member transferred '
          type: string
        cashOnlyTransfer:
          $ref: '#/components/schemas/booleanType'
        paymentTaxableOverseas:
          $ref: '#/components/schemas/booleanType'
        reasonNoOverseasTransfer:
          description: "The transferred value does not exceed the members available\
            \ overseas transfer allowance at the time of transfer and: \\n01 - The\
            \ QROPS is an occupational pension scheme and the individual is an employee\
            \ of the sponsoring employer\\n02 - The QROPS is an overseas public service\
            \ scheme and the individual is employed by that public service \\n03 -\
            \ The QROPS is a pension scheme of an international organisation and the\
            \ individual is employed by that international organisation \\n04 - Both\
            \ the individual and QROPS are resident in the same country "
          maxItems: 4
          minItems: 0
          uniqueItems: true
          type: array
          items:
            enum:
            - "01"
            - "02"
            - "03"
            - "04"
            type: string
        taxableOverseasTransferDetails:
          $ref: '#/components/schemas/taxableOverseasTransferDetailsType'
        typeOfAssets:
          $ref: '#/components/schemas/typeOfAssetsType'
      additionalProperties: false
    typeOfAssetsType:
      type: object
      properties:
        recordVersion:
          $ref: '#/components/schemas/versionType'
        cashAssets:
          $ref: '#/components/schemas/booleanType'
        cashValue:
          $ref: '#/components/schemas/currencyType'
        unquotedShareAssets:
          $ref: '#/components/schemas/booleanType'
        moreUnquoted:
          $ref: '#/components/schemas/booleanType'
        quotedShareAssets:
          $ref: '#/components/schemas/booleanType'
        moreQuoted:
          $ref: '#/components/schemas/booleanType'
        propertyAsset:
          $ref: '#/components/schemas/booleanType'
        moreProp:
          $ref: '#/components/schemas/booleanType'
        otherAsset:
          $ref: '#/components/schemas/booleanType'
        moreAsset:
          $ref: '#/components/schemas/booleanType'
        unquotedShares:
          $ref: '#/components/schemas/unquotedSharesType'
        quotedShares:
          $ref: '#/components/schemas/quotedSharesType'
        propertyAssets:
          $ref: '#/components/schemas/propertyAssetsType'
        otherAssets:
          $ref: '#/components/schemas/otherAssetsType'
      additionalProperties: false
    ukPostCodeType:
      description: Only use this field if it is a UK address.
      maxLength: 10
      minLength: 1
      pattern: "^([A-Z]{1,2}[0-9][0-9A-Z]?\\s?[0-9][A-Z]{2}|BFPO\\s?[0-9]{1,3})$"
      type: string
    unquotedSharesType:
      minItems: 0
      type: array
      items:
        type: object
        properties:
          recordVersion:
            $ref: '#/components/schemas/versionType'
          unquotedValue:
            $ref: '#/components/schemas/currencyType'
          unquotedShareTotal:
            $ref: '#/components/schemas/integer7DigitsMinimum0Type'
          unquotedCompany:
            $ref: '#/components/schemas/string160Type'
          unquotedClass:
            $ref: '#/components/schemas/string160Type'
        additionalProperties: false
    versionType:
      pattern: "^([0-9]{3})$"
      type: string
    HIP-originEnum:
      enum:
      - HIP
      - HoD
      type: string
    HIP-failureResponse:
      required:
      - failures
      type: object
      properties:
        failures:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - type
            - reason
            type: object
            properties:
              type:
                type: string
              reason:
                type: string
            additionalProperties: false
    HIP-originResponse:
      required:
      - origin
      - response
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/HIP-originEnum'
        response:
          $ref: '#/components/schemas/HIP-failureResponse'
      additionalProperties: false
  examples:
    podsQROPSCreateSample422ErrorResponse:
      value:
        errors:
          processingDate: 2022-01-31T09:26:17Z
          code: "003"
          text: Request could not be processed
    podsQROPSCreateSampleRequestData:
      value:
        reportDetails:
          pstr: 00000000AA
          qtStatus: Submitted
          qtReference: QT123452
          qtDigitalStatus: "Yes"
        transferringMember:
          memberDetails:
            foreName: Joey
            lastName: Banjo
            dateOfBirth: 2025-03-14
            nino: AS156939D
            principalResAddDetails:
              addressDetails:
                addressLine1: 1 Hacienda Way
                addressLine2: Madrid
                addressLine3: "01055"
                ukPostCode: A00AA
                country: AD
              poBoxNumber: AB
            memberResidencyDetails:
              memUkResident: "No"
              memEverUkResident: "Yes"
              lastPrincipalAddDetails:
                addressDetails:
                  addressLine1: 1 Hacienda Way
                  addressLine2: Madrid
                  addressLine3: "01055"
                  addressLine4: 01 D
                  ukPostCode: A00AA
                dateMemberLeftUk: 2025-03-14
        transferDetails:
          recordVersion: "001"
          transferAmount: 9999999.99
          allowanceBeforeTransfer: 9999999.99
          dateMemberTransferred: 2025-03-14
          cashOnlyTransfer: "No"
          paymentTaxableOverseas: "No"
          reasonNoOverseasTransfer:
          - "01"
          - "02"
          taxableOverseasTransferDetails:
            whyTaxableOT: "01"
            applicableExclusion:
            - "03"
            - "04"
            amountTaxDeducted: 9.9999999999E8
            transferMinusTax: 9999999.99
          typeOfAssets:
            recordVersion: "001"
            cashAssets: "Yes"
            cashValue: 9.9999999999E8
            unquotedShareAssets: "Yes"
            moreUnquoted: "No"
            quotedShareAssets: "No"
            moreQuoted: "No"
            propertyAsset: "No"
            moreProp: "No"
            otherAsset: "No"
            moreAsset: "No"
            unquotedShares:
            - recordVersion: "001"
              unquotedValue: 9.9999999999E8
              unquotedShareTotal: 0
              unquotedCompany: John Pvt Ltd
              unquotedClass: DC
        aboutReceivingQROPS:
          qropsFullName: David Jones
          qropsRef: QROPS000012
          receivingQropsAddress:
            addressLine1: 1 Hacienda Way
            addressLine2: Madrid
            addressLine3: "01055"
            addressLine4: 01 D
            addressLine5: AT POST
            country: AD
          receivingQropsEstablishedDetails:
            qropsEstablished: AD
            qropsEstablishedOther: AB
          qropsSchemeManagerType:
            schemeManagerType: "01"
            schemeManagerAddress:
              addressLine1: 1 Hacienda Way
              addressLine2: Madrid
              addressLine3: "01055"
              addressLine4: 01 D
              addressLine5: AT POST
              country: AD
            schemeManagerEmail: jdoe@example.com
            schemeManagerPhone: "912357894"
            qropsIndividual:
              individualForename: David
              individualSurname: John
        qtDeclaration:
          submittedBy: PSA
          submitterId: "00001234"
          psaId: A0000000
        psaDeclaration:
          declaration1: true
          declaration2: true
    podsQROPSCreateSampleResponseSuccess:
      value:
        success:
          processingDate: 2022-01-31T09:26:17Z
          formBundleNumber: "119000004320"
          qtReference: QT123456
    podsQROPSGetSample422ErrorResponse:
      value:
        errors:
          processingDate: 2022-01-31T09:26:17Z
          code: "003"
          text: Request could not be processed
    podsQROPSGetSampleResponseSuccess:
      value:
        success:
          processingDate: 2022-01-31T09:26:17Z
          pstr: 12345621AA
          qtDetails:
            qtVersion: "001"
            qtStatus: Compiled
            receiptDate: 2022-01-31T09:26:17Z
            qtReference: QT321467
            qtTransferDate: 2024-03-14
            qtDigitalStatus: AB
          transferringMember:
            memberDetails:
              foreName: Joey
              lastName: Banjo
              dateOfBirth: 2025-03-14
              nino: AS156939D
              principalResAddDetails:
                addressDetails:
                  addressLine1: 1 Hacienda Way
                  addressLine2: Madrid
                  addressLine3: "01055"
                  ukPostCode: A00AA
                  country: AD
                poBoxNumber: AB
              memberResidencyDetails:
                memUkResident: "No"
                memEverUkResident: "Yes"
                lastPrincipalAddDetails:
                  addressDetails:
                    addressLine1: 1 Hacienda Way
                    addressLine2: Madrid
                    addressLine3: "01055"
                    addressLine4: 01 D
                    ukPostCode: A00AA
                  dateMemberLeftUk: 2025-03-14
          transferDetails:
            recordVersion: "001"
            transferAmount: 99999.99
            allowanceBeforeTransfer: 9999999.99
            dateMemberTransferred: 2025-03-14
            cashOnlyTransfer: "No"
            paymentTaxableOverseas: "No"
            reasonNoOverseasTransfer:
            - "01"
            - "02"
            taxableOverseasTransferDetails:
              whyTaxableOT: "01"
              applicableExclusion:
              - "03"
              - "04"
              amountTaxDeducted: 9.9999999999E8
              transferMinusTax: 9999999.99
            typeOfAssets:
              recordVersion: "001"
              cashAssets: "Yes"
              cashValue: 9.9999999999E8
              unquotedShareAssets: "Yes"
              moreUnquoted: "No"
              quotedShareAssets: "No"
              moreQuoted: "No"
              propertyAsset: "No"
              moreProp: "No"
              otherAsset: "No"
              moreAsset: "No"
              unquotedShares:
              - recordVersion: "001"
                unquotedValue: 9.9999999999E8
                unquotedShareTotal: 0
                unquotedCompany: John Pvt Ltd
                unquotedClass: DC
          aboutReceivingQROPS:
            qropsFullName: David Jones
            qropsRef: QROPS000012
            receivingQropsAddress:
              addressLine1: 1 Hacienda Way
              addressLine2: Madrid
              addressLine3: "01055"
              addressLine4: 01 D
              addressLine5: AT POST
              country: AD
            receivingQropsEstablishedDetails:
              qropsEstablished: AD
              qropsEstablishedOther: AB
            qropsSchemeManagerType:
              schemeManagerType: "01"
              schemeManagerAddress:
                addressLine1: 1 Hacienda Way
                addressLine2: Madrid
                addressLine3: "01055"
                addressLine4: 01 D
                addressLine5: AT POST
                country: AD
              schemeManagerEmail: jdoe@example.com
              schemeManagerPhone: "912357894"
              qropsIndividual:
                individualForename: David
                individualSurname: John
          qtDeclaration:
            submittedBy: PSA
            submitterId: "00001234"
            psaId: A0000000
          psaDeclaration:
            declaration1: true
            declaration2: true
  headers:
    correlationidResponseType:
      description: "Unique alphanumeric number used for correlation purposes, generated\
        \ by the originating system and conforming to 36-character UUID (formatted)."
      required: false
      deprecated: false
      style: simple
      explode: false
      schema:
        pattern: "^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$"
        type: string
      example: f0bd1f32-de51-45cc-9b18-0520d6e3ab1a
  securitySchemes:
    oAuth2:
      type: oauth2
      description: OAuth2 Client Credentials Flow
      flows:
        clientCredentials:
          tokenUrl: /tokenUrl/not-required
          scopes:
            write:qrops-transfer: Qualifying Recognised Overseas Pension Scheme Transfer
            read:qrops-transfer: Qualifying Recognised Overseas Pension Scheme Transfer
